###通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的；
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  profiles:
    active: prod
server:
  port: 8082
info:
  name: ylw
  motto: 一个人走到何种境地，全都因为自己！